name: CS102 Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black mypy pylint isort build
        if [ -f requirements.txt ]
        then
          pip install -r requirements.txt
        fi
    - name: Run black
      run: |
        black -l 100 --check --diff --color --exclude "test*" homework07
    - name: Run pylint
      run: |
        pylint homework07 --exit-zero
    - name: Run mypy
      run: |
        cd homework07; mypy httpserver --ignore-missing-imports --strict
    - name: Run pytests
      run: |
        cd homework07/httpserver; python -m build;pip install dist/httpserver-0.0.1-py3-none-any.whl --force-reinstall
        cd ../static_server; python static_server.py &
        python -m pytest
